# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'PAQ' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

  # Pods for PAQ
  pod 'UICircularProgressRing'

  target 'PAQTests' do
    inherit! :search_paths
    # Pods for testing
  end

end
